# Generated by Django 5.2.1 on 2025-05-09 12:11

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('max_steps', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agents.agentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPersonality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalities', to='agents.agentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='agents.agentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_policy', models.CharField(blank=True, max_length=20, null=True)),
                ('history_length', models.IntegerField(blank=True, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='agents.agentconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ChatPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('chat_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_prompts', to='agents.chatsettings')),
            ],
        ),
        migrations.CreateModel(
            name='InitialMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('chat_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_messages', to='agents.chatsettings')),
            ],
        ),
        migrations.CreateModel(
            name='NodeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('max_tokens', models.IntegerField(blank=True, null=True)),
                ('top_p', models.FloatField(blank=True, null=True)),
                ('top_k', models.IntegerField(blank=True, null=True)),
                ('frequency_penalty', models.FloatField(blank=True, null=True)),
                ('presence_penalty', models.FloatField(blank=True, null=True)),
                ('stop_sequences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('use_custom_api_key', models.BooleanField(default=False)),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_configurations', to='agents.agentconfig')),
            ],
        ),
    ]
