version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: agentdock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'password>0'
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
