export const REDUX_STATES = {
  DEFAULT_GET_KEY: 'GET',
  DEFAULT_POST_KEY: 'POST',
  DEFAULT_PUT_KEY: 'PUT',
  DEFAULT_PATCH_KEY: 'PATCH',
  DEFAULT_DELETE_KEY: 'DELETE',
  DEFAULT_SELECTED_KEY: 'SELECTED',
  LOADING: '_LOADING',
  ERROR: '_ERROR',
  RESPONSE: '_RESPONSE',
  PARAMS: '_PARAMS',
};