# Generated by Django 5.2.1 on 2025-05-11 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI')], default='groq', max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('max_tokens', models.PositiveIntegerField(default=500)),
                ('temperature', models.FloatField(default=0.7)),
                ('timeout', models.PositiveIntegerField(default=10)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('api_key', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(default='', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('system_message', models.TextField(blank=True, default='You are a helpful AI assistant with access to tools.', null=True)),
                ('n_messages', models.PositiveIntegerField(default=5)),
                ('mcp_server', models.JSONField(default=dict)),
                ('llm', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.llmconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='app.agentconfig')),
            ],
        ),
    ]
