# Generated by Django 5.2.1 on 2025-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chathistory_delete_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentconfig',
            name='n_messages',
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='n_history_messages',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
