# Generated by Django 5.2.1 on 2025-05-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_agentconfig_n_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='max_tokens',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
