# Generated by Django 5.2.1 on 2025-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_agentactivitylog_agentmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='role_order',
            field=models.IntegerField(choices=[(0, 'Human'), (1, 'AI')], default=0),
        ),
    ]
