# Generated by Django 5.2.1 on 2025-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chathistory_role_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentconfig',
            name='n_history_messages',
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='n_history_messages',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
